# -*- mode: python; -*-
VERSION = '1.0'

################################################################################ 
# Closure - IO
# Copyright 2006 Google Inc.
# All Rights Reserved.
# Author: pupius@google.com (Daniel Pupius) 
#
# This package contains code for managing I/O.  Cookies, RPC calls etc.
#
################################################################################
