// Copyright 2006 Google Inc.
// All Rights Reserved.
//
// This file has been auto generated by builddeps.py
// Please do not edit

goog.addDependency('base.js', [], []);
goog.addDependency('base_test.js', [], []);
goog.addDependency('userAgent.js', ['goog.userAgent'], []);
goog.addDependency('deps.js', [], []);
goog.addDependency('draft.js', [], []);
goog.addDependency('io/cookies.js', [], []);
goog.addDependency('io/xmlhttp.js', ['goog.io.XmlHttp'], []);
goog.addDependency('structs/circularbuffer.js', [], []);
goog.addDependency('structs/map.js', ['goog.structs.Map'], []);
goog.addDependency('structs/queue.js', [], []);
goog.addDependency('structs/set.js', ['goog.structs.Set'], ['goog.structs.Map', 'goog.array']);
goog.addDependency('util/array.js', ['goog.array'], []);
goog.addDependency('util/browser.js', [], []);
goog.addDependency('util/date.js', [], []);
goog.addDependency('util/dom.js', [], []);
goog.addDependency('util/math.js', [], []);
goog.addDependency('util/string.js', ['goog.string'], []);
goog.addDependency('util/style.js', [], []);
goog.addDependency('util/uid.js', [], []);
goog.addDependency('util/uri.js', [], []);
goog.addDependency('util/window.js', ['goog.window'], []);
goog.addDependency('util/object.js', [], []);
goog.addDependency('events/event.js', ['goog.events.Event'], []);
goog.addDependency('events/events.js', ['goog.events'], ['goog.events.Event', 'goog.events.Listener', 'goog.array']);
goog.addDependency('events/eventtarget.js', ['goog.events.EventTarget'], ['goog.events']);
goog.addDependency('events/listener.js', ['goog.events.Listener'], []);
goog.addDependency('fx/dom.js', ['goog.fx.dom', 'goog.fx.dom.PredefinedEffect', 'goog.fx.dom.Slide', 'goog.fx.dom.SlideFrom', 'goog.fx.dom.Scroll', 'goog.fx.dom.Resize', 'goog.fx.dom.Fade', 'goog.fx.dom.FadeOut', 'goog.fx.dom.FadeOutAndHide', 'goog.fx.dom.FadeIn', 'goog.fx.dom.FadeInAndShow', 'goog.fx.dom.BgColorTransform', 'goog.fx.dom.ColorTransform'], ['goog.fx', 'goog.events']);
goog.addDependency('fx/fx.js', ['goog.fx', 'goog.fx.Animation', 'goog.fx.AnimationEvent'], ['goog.events.EventTarget', 'goog.array']);
