# -*- mode: python; -*-
VERSION = '1.0'

################################################################################ 
# Closure - Color parsing and conversion
# Copyright 2006 Google Inc.
# All Rights Reserved.
# Author: pupius@google.com (Daniel Pupius)  
#
# This package contains methods for converting colors from RGB -> hex -> hsl.
#
################################################################################

js_library(name='color',
           srcs=['color.js'],
           deps=['//javascript/closure:base'])
           
js_library(name='names',
           srcs=['names.js'],
           deps=['//javascript/closure:base'])