/* Copyright 2008 Google Inc.  All Rights Reserved. */ (function() {
var k=false,n=true,ca=undefined,ga=String,q=document,r=Math;function ia(a,j){return a.innerHTML=j}function ja(a,j){return a.value=j}function ka(a,j){return a.backgroundColor=j}function na(a,j){return a.returnValue=j}function oa(a,j){return a.onclick=j}var u="push",x="length",ra="split",sa="floor",y="getElementById",A="charAt",ta="userAgent",D="indexOf",J="style",ua="charCodeAt",T="substring",V="join",va=n,W=window,X,wa,xa;function Ca(){X=W.document;wa=X.documentElement;xa=X.body};function Da(a,j){var l=j||q,h=l.childNodes;for(var c=0;c<h[x];c++){var E=h[c];if(E===a){l.removeChild(a);return n}}for(var c=0;c<h[x];c++){var E=h[c];if(E&&Da(a,E))return n}return k}function Ea(a){if(!a)return-1;var j=a.offsetWidth,l=a.clip;return j||(l?l.width:-1)}function Fa(a){if(!a)return-1;var j=a.offsetHeight,l=a.clip;return j||(l?l.height:-1)}function Z(a){return""+r[sa](a)+"px"}
function Ga(a){var j=[];for(var l=0;l<a[x];l++){var h=a[A](l),c=a[ua](l);j[u]("\\'\""[D](h)>=0||c>127||c<33?"&#"+c+";":h)}return j[V]("")}var Ha=0,Ia=0,Ja=0,Ka=0;if(W.Ib){Ha=Event.Na;Ia=Event.Hb;Ja=Event.Na;Ka=Event.Kb}var La=Ha|Ia|Ja;function Ta(a){return a.ctrlKey&&!a.altKey||!!(a.i&La)}function Ua(a){return a&&(a.ctrlKey||!!(a.i&Ia))}var Va={en:"",fr:"",de:""},$={};$.userAgent=navigator[ta].toLowerCase();$.t=$[ta][D]("msie")>0&&!window.opera;
$.jb=$.t&&(function(){var a=$[ta].match(/msie (\d+)/);return a&&a[x]==2&&a[1]>=7})();
$.Pa=function(a,j,l,h){var c=this,E=[],s=0;c.Mb=function(){return s};var K=k,F=k,B=k,L=-1,Q="",M=h;c.o=[];c.Pb=j;c.e=1;c.O=1;c.N={};c.C="en";Q=M?M.n():"??";var N=[{F:"\u00c01234567890m=",f:[27,27,27,27,27,27,27,27,27,27,27,27,27,69]},{F:"QWERTYUIOP\u00db\u00dd\u00dc",u:39,f:[27,27,27,27,27,27,27,27,27,27,27,27,57]},{F:"ASDFGHJKL;\u00de",f:[54,27,27,27,27,27,27,27,27,27,27,27],p:67},{F:"ZXCVBNM\u00bc\u00be\u00bf",f:[67,27,27,27,27,27,27,27,27,27,27,84]},{u:80,f:[151],s:22,p:60}],la={de:{Y:90,Z:89,
"\u00dc":192,"\u00db":109,"\u00dd":61,";":219,"=":221,"\u00bf":220,"\u00cc":59,m:191},fr:{Q:65,A:81,Z:87,W:90,"\u00dd":219,";":221,M:59,"\u00c0":222,"\u00de":192,"\u00bc":77,"\u00be":188,"\u00bf":190,"\u00df":191,"\u00db":109}},ma={189:109,187:61,186:59},R="endefr";function O(b){var f=s!=b;s=b;f&&c.P();return f}c.Rb=O;c.Qb=function(b){c.C=b;c.J();a.H()};c.Ya=function(){c.ba="";E=['<form style="margin-bottom:0" action="">'];var b=N[0];p(b.u,b.s);da(b,0);G("\u0008","Backspace",b.f[13],0.53);t(b.p);
b=N[1];p(b.u,b.s);da(b,0);t(b.p);b=N[2];p(b.u);var f=c.za();C("\u0014",f,b.f[0],H,f[x]*0.25);da(b,1);a.eb?G("\n","Enter",b.p,0.9):t(b.p);b=N[3];p(b.u,b.s);G("\u0010","Shift",b.f[0],0.9);da(b,1);G("\u0111","Alt+Ctrl",b.f[11],0.85);t(b.p);if(a.gb){b=N[4];p(b.u,b.s);C(" "," ",b.f[0],r.round(b.s*c.e),1);t(b.p)}g("</form>");c.ba=E[V]("")};c.tb=function(){return R[D](c.C)+c.o[V]("")};c.wa=function(b){if(b){var f=b[ua](0)-48,m=b[T](b[x]-2);c.C=R[T](f,f+2);c.l(m)}else c.l(M?M.n():"??")};c.Nb=function(){return function(b){a.l(b.id)}};
c.la=function(b){M=b};c.l=function(b){var f;if(b){f=l[b]||l[b.toUpperCase()]||l[b[T](0,2).toUpperCase()];Q=b}if(!f){Q=M?M.n():"??";a.I(M);return}if(c.b&&c.b.n()==b)return;f.mb()&&a.I(f)};c.J=function(){var b=c.C=="en"?"":Va[c.C];if(c.b)a.Ja(c.b.ca(),c.b.cb(),b);else{var f="(loading...)";a.Ja(f,f,b)}};c.I=function(b){if(c.b!=b){c.b=b;c.J();c.P();var f=b.n();for(var m=0;m<c.o[x];m++)c.o[m]==f&&c.o.splice(m,1);c.o[u](f);c.o[x]>a.ib&&c.o.shift()}};c.$a=function(){c.J();a.Ha(c.ba)};function g(){for(var b=
0;b<arguments[x];b++)E[u](arguments[b])}function o(b){b&&g('<td style="width:',Z(b*c.e),'"/>')}function p(b,f){var m=($.t?c.e:0.5)*(f||30);g('<table style="table-layout:fixed;margin-left:auto;margin-right:auto;empty-cells:show;border-collapse:collapse" border="0" width="100%" cellspacing="0" cellpadding="0"><tr align="center" style="height:',Z(m),'">');b&&o(b)}function t(b){o(b);g("</tr></table>\n")}c.V="kbdButton";var z=$[ta][D]("linux")>-1,I=$[ta][D]("mac")>-1,v=z||I||$.t?18:14,H=30;function C(b,
f,m,S,ha,Ma){var Na=v*ha*c.O;if($.t&&!$.jb)Na*=c.e;m=m*c.e;var Oa=b[ua](0);c.N[Oa]=ca;var Pa="K"+Oa;g('<td style="margin:0; width:',m>0?Z(m):"1px; visibility:hidden");g('"><input type="button" class="',c.V,'" id="',Pa);g('" name="',Pa,'" value="');f!="\u0000"&&g(Ga(f));g('" style="width:100%;height:',Z(S));g(";font-size:",Z(Na));Ma&&g(";",Ma);g('"/></td>')}function G(b,f,m,S){C(b,f,m,H,S||1)}function da(b,f){for(var m=0;m<b.F[x];m++){var S=b.F[A](m);G(S,S,b.f[m+f],b.s)}}c.qa=function(b){return c.b&&
c.b.Ca?c.b.qa(b):{aa:b}};function Y(){c.b&&c.b.Ta()}function ea(b){a.Ga(b)}var pa={back:1,aa:""},ya={K8:function(){Y();ea(pa)},K10:function(){a.pb()},K16:function(){F=!F;U(!fa())},K20:function(){P()},K273:function(){aa()}};c.Ra=function(b){ea(c.qa(b.value))};function za(b){return function(){b(this);$a(this)}}c.ma=function(){for(var b in c.N){var f="K"+b;if(b[ua](0)<58){var m=q[y](f);c.N[b]=m;if(m)oa(m,za(ya[f]||c.Ra))}}};function fa(){return(s&1)==1}function ba(){return(s&2)==2}function d(){return(s&
12)==12}function e(){return(fa()?"s":"")+(d()?"c":"")+(ba()?"l":"")}function i(b){return c.N[b]}c.qb=function(b){if(b<0)return k;c.e=b;H=r.round(30*c.e);c.Ya();a.Ha(c.ba);c.P();a.rb(b/c.O);return n};c.U=function(b){if(a){var f=a.bb();return b||f<5&&(f>c.e*1.1||f<c.e)&&f>0.3?c.qb(f):k}};c.za=function(){return c.b&&c.b.ua?c.b.ua[ba()?"l":""]:"C/Lk"};function w(b,f){if(b&&b[J])b[J].fontWeight=f?"bold":""}c.P=function(){if(!c.b)return;var b=c.b.ab(e()),f=i(20);if(f){ja(f,c.za());f.defaultValue=f.value;
w(f,ba())}w(i(16),fa());w(i(273),d());if(b)for(var m in b){var S=b[m];if(typeof S==="string"){var ha=i(m[ua](0));if(ha)ja(ha,b[m])}}};function P(){O(s^2);a.j()}function U(b){if(b==fa())return n;var f=b?1:0;O(s&-2|f);a.j();return k}function aa(b){O(b||!d()?s|12:s&-13);a.j()}function Aa(b){var f=b.which||b.keyCode||b.charCode,m=la[c.C];if(m)f=m[ga.fromCharCode(f)]||f;return ma[f]||f}function qa(b){return function(f){f=f||W.event;na(f,b(f));return f.returnValue}}var ab={G:function(){a.Db()},"\u00bc":function(){a.Ea(Q,
-1)},"\u00be":function(){a.Ea(Q,1)}};function bb(b){if(s!=4)return k;var f=ga.fromCharCode(b),m=ab[f];if(!m)return k;m();return n}function Ba(){return a&&a.Da&&a.Da()}var Qa=qa(function(b){if(!Ba())return n;var f=Aa(b);U(f!=16&&(f==16||b.shiftKey||!!(b.i&Ka)));K=k;F=k;Ua(b)||O(s&-5);f==18||b&&(b.altKey||!!(b.i&Ja))||O(s&-9);if(f==224||s&16){O(s&-17);return n}if(Ta(b)){!!(b.i&Ha)&&aa(k);return n}B=k;f==20&&P();return k}),Ra=qa(function(b){var f=Aa(b);if(!Ba())return na(b,n);K=n;var m=b.target||b.srcElement;
a.Ia(m);if(m)try{m.onfocus()}catch(S){}if(f==20)return na(b,n);if(f==224||s&16){O(s|16);return na(b,n)}if(!!(b.i&Ha)){aa(!!(b.i&Ha));return na(b,n)}Ua(b)&&O(s|4);(f==18||b&&(b.altKey||!!(b.i&Ja)))&&O(s|8);if(Ta(b)||f==17||f==18)return na(b,!bb(f));if(f==16)return na(b,U(n));return na(b,cb(b,f,m))});function cb(b,f,m){B=n;L=f;F||U(f==16||b.shiftKey||!!(b.i&Ka));F=k;var S=i(f);if(S){a.j();var ha=W._kbdSI;m&&ha&&c.V!=m.className&&ha(m);S.onclick()}else{K=k;Y()}return!S}var Sa=qa(function(){if(!Ba())return n;
if(s&16)return n;if(s==4)return n;if(K||!B){K=k;return k}if(Ba()&&L!=20){var b=i(L);if(b){if(B)Y();else{b.onclick();B=k}return k}}Y();K=k;return n}),db,eb,fb;c.S=function(){if(X.onkeyup!=Qa){db=X.onkeyup;X.onkeyup=Qa}if(X.onkeydown!=Ra){eb=X.onkeydown;X.onkeydown=Ra}if(X.onkeypress!=Sa){fb=X.onkeypress;X.onkeypress=Sa}};c.pa=function(){c.S()};function $a(b){var f=b[J].backgroundColor;ka(b[J],"cfcfcf");b[J].padding=0;b.xa=b.xa||function(){ka(b[J],f)};W.setTimeout(b.xa,70)}};function Wa(a){return function(){return a}}$.sa=function(a,j){return j==a?a:a[D]("<abbr")>=0?a:['<abbr style="border-style:none" title="',j,'">',a,"</abbr>"][V]("")};
$.ra=function(a){var j=["","s","l","c","sc","sl","cl","scl"],l=["\u00c0","1","2","3","4","5","6","7","8","9","0","m","=","Q","W","E","R","T","Y","U","I","O","P","\u00db","\u00dd","\u00dc","A","S","D","F","G","H","J","K","L",";","\u00de","Z","X","C","V","B","N","M","\u00bc","\u00be","\u00bf"],h=this;h.ia=a.name;h.Ca=k;var c=a.Tb,E=a.Eb,s="??",K="??",F={},B={},L={};h.xb=a.na;for(var Q=0;Q<j[x];Q++)F[j[Q]]={};function M(g){var o;if(g[D](":")>0){var p=g[ra](/:/);o=p[0][ra](/,/);var t=p[1];h.ia=p[p[x]>
2?2:1]}else o=g[ra](/,/);h.id=o[0];s=o[x]>1?o[1]:h.id;K=$.sa(h.ia,t)}h.ca=function(){return c?c():K};h.Cb=function(g){return function(){var o=[$.sa("<b>&nbsp;"+h.ia+"</b>",E)];for(var p in g){var t=g[p];if(typeof t==="string"&&s!=p){o[x]>0&&o[u]("&nbsp;&nbsp;");o[u]($.X(t,"s2"+p,"_kbdS2('"+p+"');"))}}return o[V]("")}};h.cb=function(){return h.xb||h.ca()};h.n=function(){return s};function N(g){for(var o in g){var p=g[o],t=o[ra](/,/);t[V](",")!=o&&t[u]("");var z={};if(p){var I=p[""];if(I)for(var v=
0;v<I[x];v++)z[l[v]]=I[A](v);else for(var H in p){var C=p[H];if(typeof C!="string")continue;if(H[x]==1)z[H[A](0)]=C;else for(var v=0;v<H[x];v++)z[H[A](v)]=C[A](v)}}for(var v=0;v<t[x];v++){var G=t[v];if(G=="-")G="";var da=F[G];for(var Y=0;Y<l[x];Y++){var ea=l[Y];da[ea]=z[ea]?z[ea]:""}}}}h.Ba=function(g){if(g.ga){N(g.ga);if(g.Sa)h.ua=g.Sa;if(g.Fb)L=g.Fb;la(g.transform);h.d="";h.Ba=h.mb=Wa(n);h.Ca=n;h.lb=function(){return g.direction=="rtl"}}};function la(g){if(!g)return;for(var o in g){var p=g[o];typeof p===
"string"&&ma("",o,p)}}function ma(g,o,p){var t=o[D]("[");if(t<0)O(g+o,p);else{var z=o[D]("]"),I=o[T](0,t),v=o[T](t+1,z),H=o[T](z+1);for(var C=0;C<v[x];C++)ma(g+I+v[A](C),H,p)}}var R=0;function O(g,o){R=r.max(R,g[x]);for(var p=1;p<g[x];p++){var t=g[T](0,p);if(typeof B[t]=="undefined")B[t]="-"}B[g]=o.replace("\u0000",g[A](0)).replace("\u0001",g[A](1)).replace("\u0002",g[A](2))}h.ab=function(g){return F[g]};h.qa=function(g){if(L[g])g=L[g];var o=0;if(!B["*"])for(o=0;o<h.d[x]&&!B[h.d[A](o)];o++);if(o>=
h.d[x])return h.d=g;if(o>0)h.d=h.d[T](o);var p=0;for(var t=0;t<g[x];t++){h.d+=g[A](t);p++;var z=h.d,I=B[z];while(I===ca&&z[x]>0){z=z[T](1);I=B[z]}if(I!==ca&&I!="-"){var v=I+g[T](t+1),H=z[x]-p,C=h.d[x]-z[x],G=r.max(0,C+v[x]-R);h.d=G>=C?v:h.d[T](G,C)+v;return{back:H,aa:v}}}return g};h.Ta=function(){h.d=""};M(a.id);a.ga&&h.Ba(a)};var Xa="</tr></table>";function Ya(a){var j=[];if(a<=0)return"0";while(a>0){var l=a%62;j[u](ga.fromCharCode(l+(l<10?48:l<36?55:61)));a=r[sa](a/62)}return j.reverse()[V]("")}function Za(a){var j=0;if(!a)return 0;for(var l=0;l<a[x];l++){var h=a[ua](l),c=h-(h<58?48:h<91?55:61);j=j*62+c}return j}function gb(a){a&&(a.stopPropagation?a.stopPropagation():(a.cancelBubble=n))}function hb(a){if(!a)return"";var j=a.match(/(^|;)KBD=([^;]+)/);return!j?"":j[2]}
$.X=function(a,j,l){return['<a style="text-decoration:none;cursor:pointer;font-size:80%;color:',$.a.linkColor,'" onmouseover="this.style.textDecoration=\'underline\'" onmouseout="this.style.textDecoration=\'none\'" ',j?'id="'+j+'" ':"",l?'onclick="'+l+'"':"",">",a,"</a>"][V]("")};var ib="vMmh",jb={v:435,M:330,m:280,h:0};
$.Oa=function(){var a=this,j,l,h,c,E=k,s="",K={},F=1,B=1,L=1;a.r=-1;a.D=-1;var Q=-1,M=-1;a.scrollX=0;a.scrollY=0;a.$=n;a.zb="left";a.k=0;a.q=0;a.va="h";a.c="h";a.L="h";a.fa={};var N=[],la=0;a.ib=1;a.yb="black";a.linkColor="blue";a.bgColor="#eaf2ff";a.ya="#d7e6ff";a.z="";a.w="";a.scale=1;a.Fa=$.t?"absolute":"fixed";a.hb=n;a.na="";a.gb=k;a.eb=k;a.Wa=function(d){for(var e in d){var i=e[A](0)=="_"?e[T](1):e;if(d.hasOwnProperty(e)&&typeof a[i]!="undefined")a[i]=d[e]}};function ma(){var d=X.createElement("div"),
e=d[J];e.position=a.Fa;e.visibility="hidden";e.width="390px";e.zIndex=20001;ka(e,a.ya);ia(d,'<div dir="ltr" id="kbda"><div id="kbd_0"/></div>');d.setAttribute("id","kbd");xa.appendChild(d);return d}a.Ka=[function(){j=ma();if(!c)c=a.ea=new $.Pa(a,K,a.fa,h);a.ea.O=a.scale;l=j[J];l.position=a.Fa;$.ob=function(){a.kb()?a.Aa():a.R()};var d=W.onresize;function e(){$.ob();d&&d()}if(e!=d)W.onresize=e;c.$a();a.I(h,n);a.H=function(){X.cookie="KBD="+O()+";expires=July 19, 2051"};if(l.position=="absolute"){$.onscroll=
function(){a.scrollX=wa&&wa.scrollLeft;if(!a.scrollX)a.scrollX=xa.scrollLeft;a.scrollY=wa&&wa.scrollTop;if(!a.scrollY)a.scrollY=xa.scrollTop;a.ha(a.r,a.D)};var i=W.onscroll;function w(){W.onscroll=function(){W.Jb.onscroll();i&&i()}}if(i!=W.onscroll)W.onscroll=w}}];a.wb=function(){for(var d=0;d<a.Ka[x];d++)a.Ka[d](a);ka(l,a.ya)};a.bb=function(){var d=q[y]("kbd_tx");return d?Fa(d)/20:-1};a.left=function(){return j.offsetLeft};a.top=function(){return j.offsetTop};a.Ua=function(){return W.innerHeight||
wa.clientHeight||xa.clientHeight};a.Va=function(){return xa.clientWidth};function R(){a.height=Fa(j);a.Gb=Ea(j);F=a.Va()-a.Gb;B=a.ka?0:F;L=a.Ua()-a.height;Q=r[sa](F*(a.ka?a.k:1-a.k)+0.5);M=r[sa](L*(1-a.q)+0.5)}function O(){return c.tb()+"-"+Ya(r[sa](2000*a.k)*4804+r[sa](1200*a.q)*4+ib[D](a.c))}function g(d){var e=d[D]("-"),i=e+1;if(e<0){e=3;i=3}c.wa(d[T](0,e));a.k=0;a.q=0;var w=Za(d[T](i)),P=ib[A](w%4);a.Xa(r[sa](w/4));a.oa(P)}function o(d){a.La();if(!d){c.wa();return}try{g(d)}catch(e){a.La()}a.c!=
"h"&&c.U(n)}a.H=function(){};a.Ia=function(d){if(d){var e=d.onfocus;if(!e)d.onfocus=function(){W._kbdSI(d)};else if(e.toString()[D]("_kbdSI")<0)d.onfocus=function(){W._kbdSI(d);e()}}};function p(d){var e=k;for(var i=0;i<d[x];i++)e=t(d[i])||e;return e}function t(d){if(!d)return k;var e=k,i=d.nodeName.toLowerCase();if(i=="textarea"||i=="input"&&d.type.toLowerCase()=="text"){e=n;if(!d.fb){a.Ia(d);d.fb=n}}return e}function z(){Ca();var d=q[y]("kbd");d&&Da(d,X);var e=k,i=0;function w(){if(i==0){var U=
p(X.getElementsByTagName("textarea"))|p(X.getElementsByTagName("input"));if(!U)return k}i=(i+1)%10;if(!e){a.wb();o(hb(ga(X.cookie)));e=n}return c.U()}function P(){W.setTimeout(P,w()?130:1300)}P();w()}a.ja=va?z:function(){};a.ta=function(d,e){e.Ob=d;if(!a.fa[e.n()]){la++;var i=e.n();N[u](i);a.fa[i]=e;K[d]=K[d]||[];K[d][u](e)}return e};function I(d,e){for(var i=0;i<e[x];i++)a.ta(d,new $.ra(e[i]))}a.Lb=function(d){for(var e in d)I(e,d[e])};a.la=function(d){c&&d&&c.la(d);h=d};a.I=function(d,e){if(c&&
d){c.I(d);a.ka=d.lb();R();e||a.H()}};a.l=function(d){if(E){c.l(d);if(a.g)a.g.lang=d;ba(a.c);a.j()}};a.Ea=function(d,e){for(var i=0;i<N[x];i++)N[i]==d&&a.l(N[(i+N[x]+e)%N[x]])};a.j=function(){try{var d=a.g;if(d&&d[J]){var e=d[J].visibility;if(!e||e=="visible")d.focus()}}catch(i){delete a.g}};a.pb=function(){a.g&&a.g.tagName==="TEXTAREA"&&a.Ga("\n")};a.Ga=function(d){var e=0,i=d;if(typeof d!="string"){e=d.back;i=d.aa}var w=a.g;if(!w||$.t&&!w.isContentEditable)return;a.j();var P=w.value||"",U=w.selectionStart;
if(X.selection){var aa=X.selection.createRange();if(aa.parentElement()==w){aa.moveStart("character",-e);aa.text=i}aa.collapse(k);aa.select()}else if(U||U=="0"){var Aa=w.selectionEnd,qa=U>e?P[T](0,U-e):"";ja(w,qa+i+P[T](Aa,P[x]));w.selectionEnd=w.selectionStart=U+i[x]-e}else ja(w,P[x]<e?i:P[T](0,P[x]-e)+i)};function v(){var d=q[y]("kbd_t");if(d){a.vb(d);oa(q[y]("kbd_ta"),function(e){if(!pa()){fa();gb(e)}})}return d}a.vb=function(){};function H(d){return'<span style="cursor:pointer;color:#676767;font-weight:bold"> '+
d+"</span>"}a.Ja=function(d,e,i){a.Bb=pa()?d:H(a.na||e);s=i||"";G()};function C(){return s?'<font size="-2"><div style="color:'+a.yb+';border:solid 1px;height:1em;width:1.5em">&nbsp;'+s+"&nbsp;</div></font>":""}a.db=function(){return a.Bb};function G(){var d=v();if(d&&(a.hb||la>1)){ia(d,a.db());var e=q[y]("kbd_oi");if(e)ia(e,C())}}a.ma=function(){var d=q[y]("kbd_h");if(d)oa(d,function(i){a.da();gb(i)});var e=q[y]("kbd_mm");if(e)oa(e,function(i){if(a.c=="v")fa();else a.c=="M"&&za();gb(i)});c.ma()};
function da(){return a.z&&a.z[A](0)!="_"?'<td align="right">'+$.X(a.z)+"</td>":""}function Y(){return a.w&&a.w[A](0)!="_"?"<td border=1 align=right>"+$.X(a.w,"kbd_h")+"</td>":""}a.Za=function(){return(ya()?da:Y)()};a.Qa=function(d){return['<center style="margin: 0 0;font-family:arial,sans-serif;"><table id="kbdt" border="0" width="100%" style="border:none;"><tr><td><table id="kbd_ta" border="0" width="100%" style="font-size:',r.round(a.scale*100),"%",'"><tr><td><span id="kbd_tx" style="visibility:hidden;margin:0px;padding:0px">I</span></td><td id="kbd_t" align="',
a.zb,'" style="font-size:',a.Ma,a.Ab?";cursor:"+a.Ab:"",'">','</td><td align="left" id="kbd_oi" width="3px"></td>','<td style="font-size:',a.Ma,'">',a.Za(),Xa,'</td></tr><tr valign="top"><td align="center"><div id="kbd_mka" style="display:',a.c=="v"?"block":"none",'"><table border="0" style="border:none;background-color:',a.bgColor,'"><tr><td align="center">',d,"</td>",Xa,"</div></td>",Xa,"</center>"][V]("")};a.Ha=function(d){a.Ma=Z(15*a.scale);var e=q[y]("kbd_0");if(!e)return;ia(e,a.Qa(d));G();a.ma()};
a.sb=function(){R();var d=a.k,e=a.q;a.k=r.min(1,(a.ka?a.r:F-a.r)/F);a.q=r.min(1,1-a.D/L);d!=a.k&&e!=a.q&&a.H()};a.ha=function(d,e){a.r=r.min(F,r.max(0,d));a.D=r.min(L,r.max(0,e));l.left=Z(a.r+a.scrollX);l.top=Z(a.D+a.scrollY)};a.R=function(){R();var d=3;while(d-- >0&&(Q!=a.r||M!=a.D)){a.ha(Q,M);R()}};a.rb=function(d){if(a.c!="h"){var e=jb[a.c]*c.O*d+10;l.width=Z(e);l.height=Z(Fa(q[y]("kbd_0")));a.R()}};a.kb=function(){R();var d=r.abs(B-a.r)+r.abs(L-a.D);return d<90};a.Aa=function(){a.k=a.q=0;R();
a.ha(B,L);a.R();a.sb()};function ea(){return l.visibility=="visible"&&a.c!=a.L}a.Db=function(){if(ea())a.da();else a.c=="M"?fa():za()};function pa(){return"vM"[D](a.c)>=0}a.pa=function(){c.pa();E=k};a.S=function(){if(!E&&pa()){c.S();E=n}};a.Da=function(){return E};function ya(d){return"hm"[D](d||a.c)>=0}a.ub=function(){};a.oa=function(d){if(ya(d)){a.c=a.L;a.pa();a.j();if(a.c=="h"){l.visibility="hidden";c.J();return}}else c.P();if(d=="M"&&!a.$)d="v";a.c=d;c.J();var e=q[y]("kbd_mka");if(!e)return;e[J].display=
d=="v"?"block":"none";a.R();a.S();c.e=1;a.ub(d);c.U(n);a.j();l.visibility="visible"};a.La=function(){a.oa(a.va)};function za(){ba("v")}function fa(){ba(a.$?"M":"v")}function ba(d){a.oa(d);a.H();a.ea.U(n)}a.da=function(){ba(a.L)};a.Sb=function(){ba("v")}};$.a=new $.Oa;$.a.Xa=$.a.Aa;W._kbdSI=function(a){if(a&&a!=$.a.g&&a.className!=$.a.ea.V){$.a.g=a;if(a.prompt)a.prompt=null;a.lang&&$.a.l(a.lang)}};W._kbdHide=function(){$.a.da()};
function kb(a,j,l){$.a.Wa({$:k,va:"m",L:"m",z:a||"on",w:j||"off",na:l})}$.a.nb=function(a){var j=$.a.ta("-",new $.ra(a));j.ca=j.Cb({});$.a.la(j);kb(a.z,a.w)};function lb(a){$.a.nb(a)}W._kbdS2=function(a){$.a.l(a)};var mb=W.onload;function nb(){$.a.ja&&$.a.ja();$.a.ja=null;mb&&mb()}if(!W.K||W.K!=$.K){mb=W.onload;W.onload=nb;W.K=$.K=new Date};lb({id:"AR,AR:Arabic:\u0644\u0648\u062d\u0629 \u0645\u0641\u0627\u062a\u064a\u062d \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629",Eb:"Arabic keyboard",z:"\u0646\u0634\u0637",w:"\u063a\u064a\u0631 \u0646\u0634\u0637",direction:"rtl",ga:{"scl,sc,sl,s":{"\u00c01234567890m=":"\u0651!@#$%^&*)(_+",QWER:"\u064e\u064b\u064f\u064c",T:"\u0644\u0625","YUIOP\u00db\u00dd\u00dc":"\u0625\u2018\u00f7\u00d7\u061b<>|",ASDF:"\u0650\u064d][",G:"\u0644\u0623","HJKL;\u00de":'\u0623\u0640\u060c"',
ZXCV:"~\u0652}{",B:"\u0644\u0622","NM\u00bc\u00be\u00bf":"\u0622\u2019,.\u061f"},"cl,l,c,":{"\u00c01234567890m=":"\u0630\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669\u0660-=","QWERTYUIOP\u00db\u00dd\u00dc":"\u0636\u0635\u062b\u0642\u0641\u063a\u0639\u0647\u062e\u062d\u062c\u062f\\","ASDFGHJKL;\u00de":"\u0634\u0633\u064a\u0628\u0644\u0627\u062a\u0646\u0645\u0643\u0637",ZXCV:"\u0626\u0621\u0624\u0631",B:"\u0644\u0627","NM\u00bc\u00be\u00bf":"\u0649\u0629\u0648\u0632\u0638"}}});
})()
