/* Copyright 2008 Google Inc.  All Rights Reserved. */ (function() {
var h=false,n=true,aa=undefined,da=String,p=document,r=Math;function ia(a,g){return a.innerHTML=g}function ja(a,g){return a.value=g}function ka(a,g){return a.backgroundColor=g}function na(a,g){return a.returnValue=g}function oa(a,g){return a.onclick=g}var u="push",w="length",ra="split",x="floor",A="getElementById",D="charAt",sa="userAgent",J="indexOf",T="style",ta="charCodeAt",V="substring",ua="join",va=n,W=window,X,wa,xa;function Ca(){X=W.document;wa=X.documentElement;xa=X.body};function Da(a,g){var l=g||p,j=l.childNodes;for(var c=0;c<j[w];c++){var E=j[c];if(E===a){l.removeChild(a);return n}}for(var c=0;c<j[w];c++){var E=j[c];if(E&&Da(a,E))return n}return h}function Ea(a){if(!a)return-1;var g=a.offsetWidth,l=a.clip;return g||(l?l.width:-1)}function Fa(a){if(!a)return-1;var g=a.offsetHeight,l=a.clip;return g||(l?l.height:-1)}function Y(a){return""+r[x](a)+"px"}
function Ga(a){var g=[];for(var l=0;l<a[w];l++){var j=a[D](l),c=a[ta](l);g[u]("\\'\""[J](j)>=0||c>127||c<33?"&#"+c+";":j)}return g[ua]("")}var Ha=0,Ia=0,Ja=0,Ka=0;if(W.Ob){Ha=Event.Ua;Ia=Event.Nb;Ja=Event.Ua;Ka=Event.Qb}var La=Ha|Ia|Ja;function Ta(a){return a.ctrlKey&&!a.altKey||!!(a.j&La)}function Ua(a){return a&&(a.ctrlKey||!!(a.j&Ia))}var Va={en:"",fr:"",de:""},$={};$.userAgent=navigator[sa].toLowerCase();$.u=$[sa][J]("msie")>0&&!window.opera;
$.tb=$.u&&(function(){var a=$[sa].match(/msie (\d+)/);return a&&a[w]==2&&a[1]>=7})();
$.Wa=function(a,g,l,j){var c=this,E=[],s=0;c.Tb=function(){return s};var K=h,F=h,B=h,L=-1,Q="",M=j;c.p=[];c.Wb=g;c.e=1;c.S=1;c.R={};c.D="en";Q=M?M.o():"??";var N=[{H:"\u00c01234567890m=",f:[27,27,27,27,27,27,27,27,27,27,27,27,27,69]},{H:"QWERTYUIOP\u00db\u00dd\u00dc",w:39,f:[27,27,27,27,27,27,27,27,27,27,27,27,57]},{H:"ASDFGHJKL;\u00de",f:[54,27,27,27,27,27,27,27,27,27,27,27],q:67},{H:"ZXCVBNM\u00bc\u00be\u00bf",f:[67,27,27,27,27,27,27,27,27,27,27,84]},{w:80,f:[151],t:22,q:60}],la={de:{Y:90,Z:89,
"\u00dc":192,"\u00db":109,"\u00dd":61,";":219,"=":221,"\u00bf":220,"\u00cc":59,m:191},fr:{Q:65,A:81,Z:87,W:90,"\u00dd":219,";":221,M:59,"\u00c0":222,"\u00de":192,"\u00bc":77,"\u00be":188,"\u00bf":190,"\u00df":191,"\u00db":109}},ma={189:109,187:61,186:59},R="endefr";function O(b){var f=s!=b;s=b;f&&c.V();return f}c.Yb=O;c.Xb=function(b){c.D=b;c.N();a.J()};c.hb=function(){c.da="";E=['<form style="margin-bottom:0" action="">'];var b=N[0];q(b.w,b.t);ea(b,0);G("\u0008","Backspace",b.f[13],0.53);t(b.q);
b=N[1];q(b.w,b.t);ea(b,0);t(b.q);b=N[2];q(b.w);var f=c.Ea();C("\u0014",f,b.f[0],H,f[w]*0.25);ea(b,1);a.ob?G("\n","Enter",b.q,0.9):t(b.q);b=N[3];q(b.w,b.t);G("\u0010","Shift",b.f[0],0.9);ea(b,1);G("\u0111","Alt+Ctrl",b.f[11],0.85);t(b.q);if(a.qb){b=N[4];q(b.w,b.t);C(" "," ",b.f[0],r.round(b.t*c.e),1);t(b.q)}i("</form>");c.da=E[ua]("")};c.Bb=function(){return R[J](c.D)+c.p[ua]("")};c.Aa=function(b){if(b){var f=b[ta](0)-48,m=b[V](b[w]-2);c.D=R[V](f,f+2);c.n(m)}else c.n(M?M.o():"??")};c.Ub=function(){return function(b){a.n(b.id)}};
c.na=function(b){M=b};c.n=function(b){var f;if(b){f=l[b]||l[b.toUpperCase()]||l[b[V](0,2).toUpperCase()];Q=b}if(!f){Q=M?M.o():"??";a.K(M);return}if(c.b&&c.b.o()==b)return;f.vb()&&a.K(f)};c.N=function(){var b=c.D=="en"?"":Va[c.D];if(c.b)a.Qa(c.b.ea(),c.b.mb(),b);else{var f="(loading...)";a.Qa(f,f,b)}};c.K=function(b){if(c.b!=b){c.b=b;c.N();c.V();var f=b.o();for(var m=0;m<c.p[w];m++)c.p[m]==f&&c.p.splice(m,1);c.p[u](f);c.p[w]>a.sb&&c.p.shift()}};c.jb=function(){c.N();a.Na(c.da)};function i(){for(var b=
0;b<arguments[w];b++)E[u](arguments[b])}function o(b){b&&i('<td style="width:',Y(b*c.e),'"/>')}function q(b,f){var m=($.u?c.e:0.5)*(f||30);i('<table style="table-layout:fixed;margin-left:auto;margin-right:auto;empty-cells:show;border-collapse:collapse" border="0" width="100%" cellspacing="0" cellpadding="0"><tr align="center" style="height:',Y(m),'">');b&&o(b)}function t(b){o(b);i("</tr></table>\n")}c.$="kbdButton";var z=$[sa][J]("linux")>-1,I=$[sa][J]("mac")>-1,v=z||I||$.u?18:14,H=30;function C(b,
f,m,S,ha,Ma){var Na=v*ha*c.S;if($.u&&!$.tb)Na*=c.e;m=m*c.e;var Oa=b[ta](0);c.R[Oa]=aa;var Pa="K"+Oa;i('<td style="margin:0; width:',m>0?Y(m):"1px; visibility:hidden");i('"><input type="button" class="',c.$,'" id="',Pa);i('" name="',Pa,'" value="');f!="\u0000"&&i(Ga(f));i('" style="width:100%;height:',Y(S));i(";font-size:",Y(Na));Ma&&i(";",Ma);i('"/></td>')}function G(b,f,m,S){C(b,f,m,H,S||1)}function ea(b,f){for(var m=0;m<b.H[w];m++){var S=b.H[D](m);G(S,S,b.f[m+f],b.t)}}c.ta=function(b){return c.b&&
c.b.Ga?c.b.ta(b):{ca:b}};function Z(){c.b&&c.b.$a()}function fa(b){a.La(b)}var pa={back:1,ca:""},ya={K8:function(){Z();fa(pa)},K10:function(){a.yb()},K16:function(){F=!F;U(!ga())},K20:function(){P()},K273:function(){ba()}};c.Ya=function(b){fa(c.ta(b.value))};function za(b){return function(){b(this);$a(this)}}c.oa=function(){for(var b in c.R){var f="K"+b;if(b[ta](0)<58){var m=p[A](f);c.R[b]=m;if(m)oa(m,za(ya[f]||c.Ya))}}};function ga(){return(s&1)==1}function ca(){return(s&2)==2}function d(){return(s&
12)==12}function e(){return(ga()?"s":"")+(d()?"c":"")+(ca()?"l":"")}function k(b){return c.R[b]}c.zb=function(b){if(b<0)return h;c.e=b;H=r.round(30*c.e);c.hb();a.Na(c.da);c.V();a.Ab(b/c.S);return n};c.X=function(b){if(a){var f=a.lb();return b||f<5&&(f>c.e*1.1||f<c.e)&&f>0.3?c.zb(f):h}};c.Ea=function(){return c.b&&c.b.xa?c.b.xa[ca()?"l":""]:"C/Lk"};function y(b,f){if(b&&b[T])b[T].fontWeight=f?"bold":""}c.V=function(){if(!c.b)return;var b=c.b.kb(e()),f=k(20);if(f){ja(f,c.Ea());f.defaultValue=f.value;
y(f,ca())}y(k(16),ga());y(k(273),d());if(b)for(var m in b){var S=b[m];if(typeof S==="string"){var ha=k(m[ta](0));if(ha)ja(ha,b[m])}}};function P(){O(s^2);a.k()}function U(b){if(b==ga())return n;var f=b?1:0;O(s&-2|f);a.k();return h}function ba(b){O(b||!d()?s|12:s&-13);a.k()}function Aa(b){var f=b.which||b.keyCode||b.charCode,m=la[c.D];if(m)f=m[da.fromCharCode(f)]||f;return ma[f]||f}function qa(b){return function(f){f=f||W.event;na(f,b(f));return f.returnValue}}var ab={G:function(){a.Jb()},"\u00bc":function(){a.Ja(Q,
-1)},"\u00be":function(){a.Ja(Q,1)}};function bb(b){if(s!=4)return h;var f=da.fromCharCode(b),m=ab[f];if(!m)return h;m();return n}function Ba(){return a&&a.Ha&&a.Ha()}var Qa=qa(function(b){if(!Ba())return n;var f=Aa(b);U(f!=16&&(f==16||b.shiftKey||!!(b.j&Ka)));K=h;F=h;Ua(b)||O(s&-5);f==18||b&&(b.altKey||!!(b.j&Ja))||O(s&-9);if(f==224||s&16){O(s&-17);return n}if(Ta(b)){!!(b.j&Ha)&&ba(h);return n}B=h;f==20&&P();return h}),Ra=qa(function(b){var f=Aa(b);if(!Ba())return na(b,n);K=n;var m=b.target||b.srcElement;
a.Oa(m);if(m)try{m.onfocus()}catch(S){}if(f==20)return na(b,n);if(f==224||s&16){O(s|16);return na(b,n)}if(!!(b.j&Ha)){ba(!!(b.j&Ha));return na(b,n)}Ua(b)&&O(s|4);(f==18||b&&(b.altKey||!!(b.j&Ja)))&&O(s|8);if(Ta(b)||f==17||f==18)return na(b,!bb(f));if(f==16)return na(b,U(n));return na(b,cb(b,f,m))});function cb(b,f,m){B=n;L=f;F||U(f==16||b.shiftKey||!!(b.j&Ka));F=h;var S=k(f);if(S){a.k();var ha=W._kbdSI;m&&ha&&c.$!=m.className&&ha(m);S.onclick()}else{K=h;Z()}return!S}var Sa=qa(function(){if(!Ba())return n;
if(s&16)return n;if(s==4)return n;if(K||!B){K=h;return h}if(Ba()&&L!=20){var b=k(L);if(b){if(B)Z();else{b.onclick();B=h}return h}}Z();K=h;return n}),db,eb,fb;c.L=function(){if(X.onkeyup!=Qa){db=X.onkeyup;X.onkeyup=Qa}if(X.onkeydown!=Ra){eb=X.onkeydown;X.onkeydown=Ra}if(X.onkeypress!=Sa){fb=X.onkeypress;X.onkeypress=Sa}};c.sa=function(){c.L()};function $a(b){var f=b[T].backgroundColor;ka(b[T],"cfcfcf");b[T].padding=0;b.Ca=b.Ca||function(){ka(b[T],f)};W.setTimeout(b.Ca,70)}};function Wa(a){return function(){return a}}$.va=function(a,g){return g==a?a:a[J]("<abbr")>=0?a:['<abbr style="border-style:none" title="',g,'">',a,"</abbr>"][ua]("")};
$.ua=function(a){var g=["","s","l","c","sc","sl","cl","scl"],l=["\u00c0","1","2","3","4","5","6","7","8","9","0","m","=","Q","W","E","R","T","Y","U","I","O","P","\u00db","\u00dd","\u00dc","A","S","D","F","G","H","J","K","L",";","\u00de","Z","X","C","V","B","N","M","\u00bc","\u00be","\u00bf"],j=this;j.ka=a.name;j.Ga=h;var c=a.$b,E=a.Kb,s="??",K="??",F={},B={},L={};j.Eb=a.qa;for(var Q=0;Q<g[w];Q++)F[g[Q]]={};function M(i){var o;if(i[J](":")>0){var q=i[ra](/:/);o=q[0][ra](/,/);var t=q[1];j.ka=q[q[w]>
2?2:1]}else o=i[ra](/,/);j.id=o[0];s=o[w]>1?o[1]:j.id;K=$.va(j.ka,t)}j.ea=function(){return c?c():K};j.Ib=function(i){return function(){var o=[$.va("<b>&nbsp;"+j.ka+"</b>",E)];for(var q in i){var t=i[q];if(typeof t==="string"&&s!=q){o[w]>0&&o[u]("&nbsp;&nbsp;");o[u]($.aa(t,"s2"+q,"_kbdS2('"+q+"');"))}}return o[ua]("")}};j.mb=function(){return j.Eb||j.ea()};j.o=function(){return s};function N(i){for(var o in i){var q=i[o],t=o[ra](/,/);t[ua](",")!=o&&t[u]("");var z={};if(q){var I=q[""];if(I)for(var v=
0;v<I[w];v++)z[l[v]]=I[D](v);else for(var H in q){var C=q[H];if(typeof C!="string")continue;if(H[w]==1)z[H[D](0)]=C;else for(var v=0;v<H[w];v++)z[H[D](v)]=C[D](v)}}for(var v=0;v<t[w];v++){var G=t[v];if(G=="-")G="";var ea=F[G];for(var Z=0;Z<l[w];Z++){var fa=l[Z];ea[fa]=z[fa]?z[fa]:""}}}}j.Fa=function(i){if(i.ja){N(i.ja);if(i.Za)j.xa=i.Za;if(i.Lb)L=i.Lb;la(i.transform);j.d="";j.Fa=j.vb=Wa(n);j.Ga=n;j.ub=function(){return i.direction=="rtl"}}};function la(i){if(!i)return;for(var o in i){var q=i[o];typeof q===
"string"&&ma("",o,q)}}function ma(i,o,q){var t=o[J]("[");if(t<0)O(i+o,q);else{var z=o[J]("]"),I=o[V](0,t),v=o[V](t+1,z),H=o[V](z+1);for(var C=0;C<v[w];C++)ma(i+I+v[D](C),H,q)}}var R=0;function O(i,o){R=r.max(R,i[w]);for(var q=1;q<i[w];q++){var t=i[V](0,q);if(typeof B[t]=="undefined")B[t]="-"}B[i]=o.replace("\u0000",i[D](0)).replace("\u0001",i[D](1)).replace("\u0002",i[D](2))}j.kb=function(i){return F[i]};j.ta=function(i){if(L[i])i=L[i];var o=0;if(!B["*"])for(o=0;o<j.d[w]&&!B[j.d[D](o)];o++);if(o>=
j.d[w])return j.d=i;if(o>0)j.d=j.d[V](o);var q=0;for(var t=0;t<i[w];t++){j.d+=i[D](t);q++;var z=j.d,I=B[z];while(I===aa&&z[w]>0){z=z[V](1);I=B[z]}if(I!==aa&&I!="-"){var v=I+i[V](t+1),H=z[w]-q,C=j.d[w]-z[w],G=r.max(0,C+v[w]-R);j.d=G>=C?v:j.d[V](G,C)+v;return{back:H,ca:v}}}return i};j.$a=function(){j.d=""};M(a.id);a.ja&&j.Fa(a)};var Xa="</tr></table>";function Ya(a){var g=[];if(a<=0)return"0";while(a>0){var l=a%62;g[u](da.fromCharCode(l+(l<10?48:l<36?55:61)));a=r[x](a/62)}return g.reverse()[ua]("")}function Za(a){var g=0;if(!a)return 0;for(var l=0;l<a[w];l++){var j=a[ta](l),c=j-(j<58?48:j<91?55:61);g=g*62+c}return g}function gb(a){a&&(a.stopPropagation?a.stopPropagation():(a.cancelBubble=n))}function hb(a){if(!a)return"";var g=a.match(/(^|;)KBD=([^;]+)/);return!g?"":g[2]}
$.aa=function(a,g,l){return['<a style="text-decoration:none;cursor:pointer;font-size:80%;color:',$.a.linkColor,'" onmouseover="this.style.textDecoration=\'underline\'" onmouseout="this.style.textDecoration=\'none\'" ',g?'id="'+g+'" ':"",l?'onclick="'+l+'"':"",">",a,"</a>"][ua]("")};var ib="vMmh",jb={v:435,M:330,m:280,h:0};
$.Va=function(){var a=this,g,l,j,c,E=h,s="",K={},F=1,B=1,L=1;a.r=-1;a.F=-1;var Q=-1,M=-1;a.scrollX=0;a.scrollY=0;a.ba=n;a.Gb="left";a.g=0;a.l=0;a.ya="h";a.c="h";a.P="h";a.ia={};var N=[],la=0;a.sb=1;a.Fb="black";a.linkColor="blue";a.bgColor="#eaf2ff";a.Da="#d7e6ff";a.C="";a.z="";a.scale=1;a.Ka=$.u?"absolute":"fixed";a.rb=n;a.qa="";a.qb=h;a.ob=h;a.cb=function(d){for(var e in d){var k=e[D](0)=="_"?e[V](1):e;if(d.hasOwnProperty(e)&&typeof a[k]!="undefined")a[k]=d[e]}};function ma(){var d=X.createElement("div"),
e=d[T];e.position=a.Ka;e.visibility="hidden";e.width="390px";e.zIndex=20001;ka(e,a.Da);ia(d,'<div dir="ltr" id="kbda"><div id="kbd_0"/></div>');d.setAttribute("id","kbd");xa.appendChild(d);return d}a.pa=[function(){g=ma();if(!c)c=a.ha=new $.Wa(a,K,a.ia,j);a.ha.S=a.scale;l=g[T];l.position=a.Ka;$.xb=function(){a.Ia()?a.fa():a.I()};var d=W.onresize;function e(){$.xb();d&&d()}if(e!=d)W.onresize=e;c.jb();a.K(j,n);a.J=function(){X.cookie="KBD="+O()+";expires=July 19, 2051"};if(l.position=="absolute"){$.onscroll=
function(){a.scrollX=wa&&wa.scrollLeft;if(!a.scrollX)a.scrollX=xa.scrollLeft;a.scrollY=wa&&wa.scrollTop;if(!a.scrollY)a.scrollY=xa.scrollTop;a.U(a.r,a.F)};var k=W.onscroll;function y(){W.onscroll=function(){W.Pb.onscroll();k&&k()}}if(k!=W.onscroll)W.onscroll=y}}];a.Db=function(){for(var d=0;d<a.pa[w];d++)a.pa[d](a);ka(l,a.Da)};a.lb=function(){var d=p[A]("kbd_tx");return d?Fa(d)/20:-1};a.left=function(){return g.offsetLeft};a.top=function(){return g.offsetTop};a.ab=function(){return W.innerHeight||
wa.clientHeight||xa.clientHeight};a.bb=function(){return xa.clientWidth};function R(){a.height=Fa(g);a.Mb=Ea(g);F=a.bb()-a.Mb;B=a.ma?0:F;L=a.ab()-a.height;Q=r[x](F*(a.ma?a.g:1-a.g)+0.5);M=r[x](L*(1-a.l)+0.5)}function O(){return c.Bb()+"-"+Ya(r[x](2000*a.g)*4804+r[x](1200*a.l)*4+ib[J](a.c))}function i(d){var e=d[J]("-"),k=e+1;if(e<0){e=3;k=3}c.Aa(d[V](0,e));a.g=0;a.l=0;var y=Za(d[V](k)),P=ib[D](y%4);a.za(r[x](y/4));a.ra(P)}function o(d){a.Ra();if(!d){c.Aa();return}try{i(d)}catch(e){a.Ra()}a.c!="h"&&
c.X(n)}a.J=function(){};a.Oa=function(d){if(d){var e=d.onfocus;if(!e)d.onfocus=function(){W._kbdSI(d)};else if(e.toString()[J]("_kbdSI")<0)d.onfocus=function(){W._kbdSI(d);e()}}};function q(d){var e=h;for(var k=0;k<d[w];k++)e=t(d[k])||e;return e}function t(d){if(!d)return h;var e=h,k=d.nodeName.toLowerCase();if(k=="textarea"||k=="input"&&d.type.toLowerCase()=="text"){e=n;if(!d.pb){a.Oa(d);d.pb=n}}return e}function z(){Ca();var d=p[A]("kbd");d&&Da(d,X);var e=h,k=0;function y(){if(k==0){var U=q(X.getElementsByTagName("textarea"))|
q(X.getElementsByTagName("input"));if(!U)return h}k=(k+1)%10;if(!e){a.Db();o(hb(da(X.cookie)));e=n}return c.X()}function P(){W.setTimeout(P,y()?130:1300)}P();y()}a.la=va?z:function(){};a.wa=function(d,e){e.Vb=d;if(!a.ia[e.o()]){la++;var k=e.o();N[u](k);a.ia[k]=e;K[d]=K[d]||[];K[d][u](e)}return e};function I(d,e){for(var k=0;k<e[w];k++)a.wa(d,new $.ua(e[k]))}a.Rb=function(d){for(var e in d)I(e,d[e])};a.na=function(d){c&&d&&c.na(d);j=d};a.K=function(d,e){if(c&&d){c.K(d);a.ma=d.ub();R();e||a.J()}};a.n=
function(d){if(E){c.n(d);if(a.i)a.i.lang=d;ca(a.c);a.k()}};a.Ja=function(d,e){for(var k=0;k<N[w];k++)N[k]==d&&a.n(N[(k+N[w]+e)%N[w]])};a.k=function(){try{var d=a.i;if(d&&d[T]){var e=d[T].visibility;if(!e||e=="visible")d.focus()}}catch(k){delete a.i}};a.yb=function(){a.i&&a.i.tagName==="TEXTAREA"&&a.La("\n")};a.La=function(d){var e=0,k=d;if(typeof d!="string"){e=d.back;k=d.ca}var y=a.i;if(!y||$.u&&!y.isContentEditable)return;a.k();var P=y.value||"",U=y.selectionStart;if(X.selection){var ba=X.selection.createRange();
if(ba.parentElement()==y){ba.moveStart("character",-e);ba.text=k}ba.collapse(h);ba.select()}else if(U||U=="0"){var Aa=y.selectionEnd,qa=U>e?P[V](0,U-e):"";ja(y,qa+k+P[V](Aa,P[w]));y.selectionEnd=y.selectionStart=U+k[w]-e}else ja(y,P[w]<e?k:P[V](0,P[w]-e)+k)};function v(){var d=p[A]("kbd_t");if(d){a.Pa(d);oa(p[A]("kbd_ta"),function(e){if(!pa()){ga();gb(e)}})}return d}a.Pa=function(){};function H(d){return'<span style="cursor:pointer;color:#676767;font-weight:bold"> '+d+"</span>"}a.Qa=function(d,e,
k){a.Hb=pa()?d:H(a.qa||e);s=k||"";G()};function C(){return s?'<font size="-2"><div style="color:'+a.Fb+';border:solid 1px;height:1em;width:1.5em">&nbsp;'+s+"&nbsp;</div></font>":""}a.nb=function(){return a.Hb};function G(){var d=v();if(d&&(a.rb||la>1)){ia(d,a.nb());var e=p[A]("kbd_oi");if(e)ia(e,C())}}a.oa=function(){var d=p[A]("kbd_h");if(d)oa(d,function(k){a.ga();gb(k)});var e=p[A]("kbd_mm");if(e)oa(e,function(k){if(a.c=="v")ga();else a.c=="M"&&za();gb(k)});c.oa()};function ea(){return a.C&&a.C[D](0)!=
"_"?'<td align="right">'+$.aa(a.C)+"</td>":""}function Z(){return a.z&&a.z[D](0)!="_"?"<td border=1 align=right>"+$.aa(a.z,"kbd_h")+"</td>":""}a.ib=function(){return(ya()?ea:Z)()};a.Xa=function(d){return['<center style="margin: 0 0;font-family:arial,sans-serif;"><table id="kbdt" border="0" width="100%" style="border:none;"><tr><td><table id="kbd_ta" border="0" width="100%" style="font-size:',r.round(a.scale*100),"%",'"><tr><td><span id="kbd_tx" style="visibility:hidden;margin:0px;padding:0px">I</span></td><td id="kbd_t" align="',
a.Gb,'" style="font-size:',a.Ta,a.Sa?";cursor:"+a.Sa:"",'">','</td><td align="left" id="kbd_oi" width="3px"></td>','<td style="font-size:',a.Ta,'">',a.ib(),Xa,'</td></tr><tr valign="top"><td align="center"><div id="kbd_mka" style="display:',a.c=="v"?"block":"none",'"><table border="0" style="border:none;background-color:',a.bgColor,'"><tr><td align="center">',d,"</td>",Xa,"</div></td>",Xa,"</center>"][ua]("")};a.Na=function(d){a.Ta=Y(15*a.scale);var e=p[A]("kbd_0");if(!e)return;ia(e,a.Xa(d));G();
a.oa()};a.Ma=function(){R();var d=a.g,e=a.l;a.g=r.min(1,(a.ma?a.r:F-a.r)/F);a.l=r.min(1,1-a.F/L);d!=a.g&&e!=a.l&&a.J()};a.U=function(d,e){a.r=r.min(F,r.max(0,d));a.F=r.min(L,r.max(0,e));l.left=Y(a.r+a.scrollX);l.top=Y(a.F+a.scrollY)};a.I=function(){R();var d=3;while(d-- >0&&(Q!=a.r||M!=a.F)){a.U(Q,M);R()}};a.Ab=function(d){if(a.c!="h"){var e=jb[a.c]*c.S*d+10;l.width=Y(e);l.height=Y(Fa(p[A]("kbd_0")));a.I()}};a.Ia=function(){R();var d=r.abs(B-a.r)+r.abs(L-a.F);return d<90};a.fa=function(){a.g=a.l=
0;R();a.U(B,L);a.I();a.Ma()};function fa(){return l.visibility=="visible"&&a.c!=a.P}a.Jb=function(){if(fa())a.ga();else a.c=="M"?ga():za()};function pa(){return"vM"[J](a.c)>=0}a.sa=function(){c.sa();E=h};a.L=function(){if(!E&&pa()){c.L();E=n}};a.Ha=function(){return E};function ya(d){return"hm"[J](d||a.c)>=0}a.Cb=function(){};a.ra=function(d){if(ya(d)){a.c=a.P;a.sa();a.k();if(a.c=="h"){l.visibility="hidden";c.N();return}}else c.V();if(d=="M"&&!a.ba)d="v";a.c=d;c.N();var e=p[A]("kbd_mka");if(!e)return;
e[T].display=d=="v"?"block":"none";a.I();a.L();c.e=1;a.Cb(d);c.X(n);a.k();l.visibility="visible"};a.Ra=function(){a.ra(a.ya)};function za(){ca("v")}function ga(){ca(a.ba?"M":"v")}function ca(d){a.ra(d);a.J();a.ha.X(n)}a.ga=function(){ca(a.P)};a.Zb=function(){ca("v")}};$.a=new $.Va;$.a.za=$.a.fa;W._kbdSI=function(a){if(a&&a!=$.a.i&&a.className!=$.a.ha.$){$.a.i=a;if(a.prompt)a.prompt=null;a.lang&&$.a.n(a.lang)}};W._kbdHide=function(){$.a.ga()};
function kb(a,g,l){$.a.cb({ba:h,ya:"m",P:"m",C:a||"on",z:g||"off",qa:l})}$.a.wb=function(a){var g=$.a.wa("-",new $.ua(a));g.ea=g.Ib({});$.a.na(g);kb(a.C,a.z)};function lb(a){$.a.wb(a)}W._kbdS2=function(a){$.a.n(a)};var mb=W.onload;function nb(){$.a.la&&$.a.la();$.a.la=null;mb&&mb()}if(!W.O||W.O!=$.O){mb=W.onload;W.onload=nb;W.O=$.O=new Date};lb({id:"AR,AR:Arabic:\u0644\u0648\u062d\u0629 \u0645\u0641\u0627\u062a\u064a\u062d \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629",Kb:"Arabic keyboard",C:"\u0646\u0634\u0637",z:"\u063a\u064a\u0631 \u0646\u0634\u0637",direction:"rtl",ja:{"scl,sc,sl,s":{"\u00c01234567890m=":"\u0651!@#$%^&*)(_+",QWER:"\u064e\u064b\u064f\u064c",T:"\u0644\u0625","YUIOP\u00db\u00dd\u00dc":"\u0625\u2018\u00f7\u00d7\u061b<>|",ASDF:"\u0650\u064d][",G:"\u0644\u0623","HJKL;\u00de":'\u0623\u0640\u060c"',
ZXCV:"~\u0652}{",B:"\u0644\u0622","NM\u00bc\u00be\u00bf":"\u0622\u2019,.\u061f"},"cl,l,c,":{"\u00c01234567890m=":"\u0630\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669\u0660-=","QWERTYUIOP\u00db\u00dd\u00dc":"\u0636\u0635\u062b\u0642\u0641\u063a\u0639\u0647\u062e\u062d\u062c\u062f\\","ASDFGHJKL;\u00de":"\u0634\u0633\u064a\u0628\u0644\u0627\u062a\u0646\u0645\u0643\u0637",ZXCV:"\u0626\u0621\u0624\u0631",B:"\u0644\u0627","NM\u00bc\u00be\u00bf":"\u0649\u0629\u0648\u0632\u0638"}}});$.a.Sb=n;$.a.s=h;$.a.Sa="move";$.a.Pa=function(a){var g=this;a.onmousedown=function(l){g.gb(l||W.event);return h};a.onblur=function(){g.Ba()}};$.a.za=function(a){var g=this;g.l=r[x](a%1201)/1200;g.g=r[x](a/1201)/2000;g.I();g.Ia()&&g.fa()};$.a.Ba=function(){var a=this;if(a.s){a.Ma();a.L();a.s=h}};$.a.gb=function(a){var g=this;g.db=a.clientX-g.left();g.eb=a.clientY-g.top();g.s=n};$.a.fb=function(a){var g=this;g.s&&g.U(a.clientX-g.db-g.scrollX,a.clientY-g.eb-g.scrollY);return!g.s};
$.a.pa[u](function(a){a.s=h;X.onmousemove=function(g){return a.fb(g||W.event)};X.onmouseup=function(){a.Ba();return h}});
})()
