# -*- mode: python; -*-
VERSION = '1.0'

################################################################################ 
# Closure - Style Utilities
# Copyright 2006 Google Inc.
# All Rights Reserved.
# Author: pupius@google.com (Daniel Pupius)  
#
# This package contains utilities for modifying and setting styles (goog.style)
#
################################################################################


js_library(name='style',
           srcs=['style.js'],
           deps=['//javascript/closure:base',
                 '//javascript/closure/dom',
                 '//javascript/closure/util:math',
                 '//javascript/closure/util:useragent',
                ])