# -*- mode: python; -*-

VERSION = '1.0'

################################################################################ 
# Closure - Autocomplete library
# Copyright 2006 Google Inc.
# All Rights Reserved.
#
# This package contains utilities for autocompleting input in forms in HTML
#
################################################################################

js_library(name='autocomplete',
           srcs=[
                 'autocomplete.js',
                 'arraymatcher.js',
                 'inputhandler.js',
                 'renderer.js',
                 'basic.js',
                 ],
           deps=['//javascript/closure:base',
                 '//javascript/closure/dom',
                 '//javascript/closure/dom:selection',
                 '//javascript/closure/dom:classes',
                 '//javascript/closure/events:eventtarget',
                 '//javascript/closure/style',
                 '//javascript/closure/util:useragent',
                 '//javascript/closure/util:string',
                 '//javascript/closure/structs',
                ])
